services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./config.yaml:/app/config.yaml 
    environment: 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: --config /app/config.yaml 
    
